### ISSUE TITLE
The pretrained model in the link is None.

### ISSUE THREAD

**Issue by Mirandl** [siyuzou/HMD-former#1]
Hi, thanks for your fantastic work! 

I followed the link you've provided in the eval.md. But there is nothing in google drive.
I know that datasets may not to be allowed to get publicly but I wonder if I could get your pretrained model, i.e. h36m.pth.
It would be a much help!
Thank you very much in advance.

**Comment by siyuzou** [comment]
Sorry for the delayed response. The Google Drive link has been set to 'general access', so it should be no problem to access the model. Maybe you need to login to your google acount to see that file, I guess?
